# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 胡涂说
email: "huziyong@gmail.com"
name: 胡涂说
description: "hutusi.com"
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://hutusi.com" # The base hostname & protocol for your site
twitter: "https://twitter.com/hutusi"
twitter_username: "hutusi"
github: "https://github.com/hutusi"
instagram: "https://instagram.com/hutusi"
facebook: "https://facebook.com/hutusi"

copyright: "胡涂说 hutusi.com"
# time:         2012-2020
icp_info: "沪ICP备19043788号-1"
# Author
author:
    name: hutusi
    url: https://hutusi.com
    email: huziyong@gmail.com

# images CDN
# images_baseurl: '/images'
images_baseurl: "https://cdn.hutusi.com/images"
# images_newurl: 'https://rmt.ladydaily.com/fetch/hutusi/storage/blog'
default_image: "/assets/images/4.jpg"
featured_image: "/site/logo-256x256.jpg"

wechat_official: "https://cdn.hutusi.com/images/site/qrcode_for_hututalk_8cm.jpg"

markdown: kramdown
# permalink: pretty
permalink: /articles/:title

articles_path: articles/
weeklies_path: weeklies/

collections:
    weeklies:
        output: true
        permalink: /weeklies/:title

# Navigators
nav_pages:
    - title: "首页"
      url: "/"
    - title: "关于"
      url: "/about/"
    - title: "文章"
      url: "/articles/"
    - title: "周刊"
      url: "/weeklies/"
    - title: "归档"
      url: "/archive/"
    - title: "订阅"
      url: "/subscription/"
# nav_page_names: ["about.md", "archive.html", "links.md", "subscription.md"]
# can be ['feeds.pub', 'xml', 'na']
nav_feed: "na"

# theme: medium-theme
# remote_theme: hutusi/mediumish-theme-jekyll

sass:
    style: compressed

plugins:
    # - jekyll-remote-theme
    - jekyll-feed
    - jekyll-paginate-v2
    - jekyll-archives
    - jekyll-sitemap
    - jekyll-redirect-from
    - jekyll-seo-tag

include:
    - _pages

exclude:
    - vendor
    - Gemfile
    - Gemfile.lock

# Pages path
defaults:
    - scope:
          path: "_pages"
      values:
          permalink: /:basename:output_ext

# Feeds
feed:
    excerpt_only: false
    posts_limit: 20
    collections:
        - weeklies

# jekyll-feed:
#     posts_limit: 20
#     excerpt_only: true
#     collections:
#         weeklies:
#             output: true
#     # categories: true
#     # tags: true
#     # collections: true
#     # output: true


# Google Analytics
google_analytics: G-MCBGNJDDPS

# Baidu Statistic
baidu_statistic: 95ca94128a63c7bb77a40c9d3b73d22c

# cnzz Statistic
cnzz_statistic: 1278872520

# Google AdSense
google_adsense: ca-pub-7800526822107892

# addthis
addthis: ra-4fa6932104ee5f3f

# pagination-v2
pagination:
    enabled: true
    per_page: 9
    sort_field: 'date'
    sort_reverse: true
    # indexpage: 'articles.html'
    # collection: weeklies
autopages:
  enabled: false
#   collections:
#     # layouts: 
#     #   - 'weeklies.html'
#     title: 'Posts in collection :coll' # :coll is replaced by the collection name
#     permalink: '/:coll'

# tag_page_data:
#     sitemap: false

# Archives
jekyll-archives:
    enabled: 
        - year
        - categories
        - tags
    layout: archive
    layouts:
        tag: tag-archive
        category: category-archive
    permalinks:
        tag: "/tag/:name/"
        category: "/category/:name/"
        year: '/:year/'

# comments
comments_engine: disqus
disqus: hutusi

giscus:
    repo: "hutusi/hutusi.github.com"
    category: "Comments"
    repo_id: "MDEwOlJlcG9zaXRvcnkzNjc5MDgy"
    category_id: "DIC_kwDOADgjas4COYln"
    mapping: "pathname"
    input_position: "top"
    theme: "light"
    lang: "en"
