# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 胡涂说
email: "huziyong@gmail.com"
description: "hutusi.com"
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://hutusi.com" # The base hostname & protocol for your site
twitter: "https://twitter.com/hutusi"
github: "https://github.com/hutusi"
instagram: "https://instagram.com/hutusi"
facebook: "https://facebook.com/hutusi"

copyright: "胡涂说 hutusi.com"
# time:         2012-2020
icp_info: "沪ICP备19043788号-1"
# Author
author:
  name: hutusi
  url: https://hutusi.com
  email: huziyong@gmail.com

# images CDN
# images_baseurl: '/images'
images_baseurl: "https://cdn.hutusi.com/images"
# images_newurl: 'https://rmt.ladydaily.com/fetch/hutusi/storage/blog'
wechat_official: "https://cdn.hutusi.com/images/site/qrcode_for_hututalk_8cm.jpg"

markdown: kramdown
# permalink: pretty
permalink: /articles/:title
paginate: 10

# Navigators
nav_page_names: ["about.md", "archive.html", "links.md", "subscription.md"]
# can be ['feeds.pub', 'xml', 'na']
nav_feed: "na"

theme: taletype
# remote_theme: hutusi/tale

sass:
  style: compressed

plugins:
  # - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-redirect-from

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Pages path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

feed:
  excerpt_only: true
  posts_limit: 10
  # posts_sort: last_modified_at

# Google Analytics
google_analytics: G-MCBGNJDDPS

# Baidu Statistic
baidu_statistic: 95ca94128a63c7bb77a40c9d3b73d22c

# cnzz Statistic
cnzz_statistic: 1278872520

# Google AdSense
google_adsense: ca-pub-7800526822107892

# addthis
addthis: ra-4fa6932104ee5f3f

# # Tagging
# tag_page_dir:         tag
# tag_page_layout:      tag_page
# tag_permalink_style:  pretty

tag_page_data:
  sitemap: false

# Archives
jekyll-archives:
  enabled: all
  layout: archive
  layouts:
    tag: tag-archive
  permalinks:
    tag: "/tag/:name/"
    category: "/category/:name/"

# comments
comments_engine: disqus
disqus: hutusi

giscus:
  repo: "hutusi/hutusi.github.com"
  category: "Comments"
  repo_id: "MDEwOlJlcG9zaXRvcnkzNjc5MDgy"
  category_id: "DIC_kwDOADgjas4COYln"
  mapping: "pathname"
  input_position: "top"
  theme: "light"
  lang: "en"

gitalk:
  client_id: "3ecf7aac87e37cbe772c"
  client_secret: "887d16569177e1f6336cce32e9c58974c2932807"
  repo: "hutusi.github.com"
  owner: "hutusi"
  admin:
    - "hutusi"
