# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       胡涂说
email:       'huziyong@gmail.com'
description: '任抛星汉归园圃，留取乾坤盛酒囊。'
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://hutusi.com' # The base hostname & protocol for your site
twitter:     'https://twitter.com/hutusi'
github:      'https://github.com/hutusi'
instagram:   'https://instagram.com/hutusi'
facebook:    'https://facebook.com/hutusi'

copyright:    'hutusi.com'
# time:         2012-2020
# Author
author:
  name:       hutusi
  url:        https://hutusi.com
  email:      huziyong@gmail.com
  
markdown:  kramdown
# permalink: pretty
permalink: /:title
paginate:  20

theme: tale

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jekyll/tagging
  - jekyll-sitemap
  - jekyll-redirect-from

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

feed:
  excerpt_only: true

# Google Analytics
google_analytics: UA-30399492-1

# comments
comments_engine: gitalk
gitalk:
  client_id: '3ecf7aac87e37cbe772c'
  client_secret: '887d16569177e1f6336cce32e9c58974c2932807'
  repo: 'hutusi.github.com'
  owner: 'hutusi'
  admin: 
    - 'hutusi'
