markdown: rdiscount
pygments: true

permalink: /blog/:year/:month/:day/:title

theme_path: themes/bootstrap
assets_path: /assets

feed: /atom.xml

include_theme_path: themes/bootstrap

follow:
    github:       https://github.com/hutusi
    twitter:      http://www.twitter.com/hutusi
    facebook:     http://www.facebook.com/hutusi
    flicker:      http://www.flicker.com/hutusi