# Site settings
title: hutusi.com

baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://hutusi.com' # the base hostname & protocol for your site
image_baseurl: 'http://7xl9fd.com1.z0.glb.clouddn.com'

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           /blog/:year/:month/:day/:title

pagination:          true
paginate:            8
paginate_path:       page/:num/

sass:
    sass_dir: _sass
    style:    compressed

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: true
        # Meta
        show_tags: true
        show_categories: true
        # Social
        share_buttons: true
        disqus: true
