# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       hutusi.com
email:       'huziyong@gmail.com'
description: 'The world is my oyster.'
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'http://hutusi.com' # The base hostname & protocol for your site
twitter:     'https://twitter.com/hutusi'
github:      'https://github.com/hutusi'
instagram:   'https://instagram.com/hutusi'
facebook:    'https://facebook.com/hutusi'

markdown:  kramdown
# permalink: pretty
permalink: /blog/:year/:month/:day/:title
paginate:  20

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-sitemap

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext