/**
 * One-shot generator: builds CSS rules for the code-group tab icons by reading
 * Iconify's logos / vscode-icons packs and embedding each icon as a data URI.
 *
 * Usage:
 *   bun scripts/generate-code-group-icons.ts > /tmp/icons.css
 * Then replace the block between the BEGIN/END markers in src/app/globals.css.
 *
 * Each icon key here corresponds to a value returned by resolveCodeGroupIcon
 * in src/lib/code-group-icons.ts. Add to both files to support a new key.
 */
import { icons as logos } from '@iconify-json/logos';
import { icons as vscodeIcons } from '@iconify-json/vscode-icons';

type IconSrc = typeof logos | typeof vscodeIcons;

const MAP: Record<string, { src: IconSrc; name: string }> = {
  npm: { src: logos, name: 'npm-icon' },
  yarn: { src: logos, name: 'yarn' },
  pnpm: { src: logos, name: 'pnpm' },
  bun: { src: logos, name: 'bun' },
  deno: { src: logos, name: 'deno' },
  typescript: { src: logos, name: 'typescript-icon' },
  javascript: { src: logos, name: 'javascript' },
  python: { src: logos, name: 'python' },
  rust: { src: logos, name: 'rust' },
  go: { src: logos, name: 'go' },
  java: { src: logos, name: 'java' },
  ruby: { src: logos, name: 'ruby' },
  php: { src: logos, name: 'php' },
  c: { src: logos, name: 'c' },
  cpp: { src: logos, name: 'c-plusplus' },
  html: { src: logos, name: 'html-5' },
  css: { src: logos, name: 'css-3' },
  json: { src: vscodeIcons, name: 'file-type-json' },
  yaml: { src: vscodeIcons, name: 'file-type-yaml' },
  markdown: { src: vscodeIcons, name: 'file-type-markdown' },
  bash: { src: logos, name: 'bash-icon' },
  docker: { src: logos, name: 'docker-icon' },
  vite: { src: logos, name: 'vitejs' },
  react: { src: logos, name: 'react' },
  vue: { src: logos, name: 'vue' },
  nextjs: { src: logos, name: 'nextjs-icon' },
  node: { src: logos, name: 'nodejs-icon' },
  tailwind: { src: logos, name: 'tailwindcss-icon' },
};

function buildSvg(src: IconSrc, name: string): string | null {
  const icon = src.icons[name];
  if (!icon) return null;
  const w = icon.width ?? src.width ?? 24;
  const h = icon.height ?? src.height ?? 24;
  // Iconify "body" is the inner content of the <svg> tag; wrap to get a full SVG.
  return `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 ${w} ${h}'>${icon.body}</svg>`;
}

function encodeDataUri(svg: string): string {
  // CSS data URIs only require `#` and `"` to be encoded; iconify bodies use
  // double-quoted attributes, so swap to single quotes (valid SVG).
  return svg.replace(/"/g, "'").replace(/#/g, '%23').replace(/\n/g, '').replace(/\s+/g, ' ');
}

const lines: string[] = [
  '/* === BEGIN: generated by scripts/generate-code-group-icons.ts — do not hand-edit === */',
];
for (const [key, { src, name }] of Object.entries(MAP)) {
  const svg = buildSvg(src, name);
  if (!svg) {
    console.error(`Missing icon: ${name}`);
    continue;
  }
  const dataUri = encodeDataUri(svg);
  lines.push(`.cg-tab[data-cg-icon="${key}"]::before {`);
  lines.push(`  content: '';`);
  lines.push(`  background-image: url("data:image/svg+xml,${dataUri}");`);
  lines.push(`}`);
}
lines.push('/* === END: generated icons === */');
console.log(lines.join('\n'));
